### PR TITLE
Update README.md to setup the repo readme

### PR DESCRIPTION
**Pull request by vatsalkesarwani12**
Added 3 solution

### CODE REVIEW

**Comment by balsikandar-shuttl** [comment]
Adding a reference is fine but let's also write an answer to these ourselves

**Comment by Shashank02051997** [comment]
@balsikandar-shuttl lets, for now, we will add reference link to all the questions, and later on we will add an answer to these questions by ourselves

**Review by Shashank02051997 — APPROVED** [review]
LGTM

**Review by happysingh23828 — APPROVED** [review]
LGTM 👍

**Pull request merged**
